---
title: "Substantial Cardiovascular Morbidity in Adults with Lower-Complexity Congenital Heart Disease is Independent of Conventional Risk Factors"
author: "Priyanka Saha"
date: "11/5/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-data, include = FALSE}
#Load dplyr, tidyr, broom, readr, stringr
library(dplyr)
library(tidyr)
library(survival)
library(survminer)
library(ggplot2)
library(tableone)
library(gtools)

#Load datasets
#Load ACHD cases and control definitions
chd <- read.csv("../../Datasets/2102CHD_and_Controls_June13.csv", sep = ",", header = T) %>%
  select(-X)

#The following code was used to sort cases into mutually exclusive subcategories of CHD.
# chd <- chd %>% select(Patient_ID, CHD, Malformation, MetaCategory) %>%
#   mutate(CHD = as.factor(CHD)) %>%
#   mutate(MetaCategory = as.factor(ifelse(CHD == 0, "CONTROL", as.character(MetaCategory)))) %>%
#   mutate(MC = "mc") %>%
#   mutate(MC = as.factor(ifelse(MetaCategory == "CONTROL", "CONTROL",
#                                ifelse(grepl("^SEVERE", MetaCategory) | grepl(",SEVERE", MetaCategory), "SEVERE",
#                                       ifelse(grepl("^NON_SEVERE", MetaCategory) | grepl(",NON_SEVERE", MetaCategory), "NON_SEVERE",
#                                              ifelse(grepl("^CODED_BAV", MetaCategory) | grepl(",CODED_BAV", MetaCategory), "CODED_BAV", "INFERRED_BAV")))))) %>%
#   mutate(MetaCategory = MC) %>%
#   mutate(CHDsubtype = as.factor(ifelse(MetaCategory == "CODED_BAV" | MetaCategory == "INFERRED_BAV", "BAV", as.character(MetaCategory)))) %>%
#   select(Patient_ID, CHD, Malformation, MetaCategory, CHDsubtype)

#Exclude CHD cases designated as Complex (aka "SEVERE")
chd <- chd %>%
  mutate_at(vars(MetaCategory, CHDsubtype), funs(as.character)) %>%
  filter(MetaCategory != "SEVERE") %>%
  mutate_at(vars(MetaCategory, CHDsubtype), funs(as.factor)) %>%
  #Remove malformation names that were listed for controls.
  mutate(Malformation = as.character(Malformation)) %>%
  mutate(Malformation = ifelse(MetaCategory == "CONTROL", "NONE", Malformation)) %>%
  mutate(Malformation = as.factor(Malformation))

#Load covariates (sociodemographics, risk factors, CVD survival data)
covariates <- read.csv("../../Datasets/Basic_attributes_and_CVD_survival_allUKB_Nov05_alternativephysicalactivitydefn.csv", sep = ",", header = T) ##...alternativephysicalactivitydefn.csv file defines Low_activity variable as positive (==1) if both vigorous activity and moderate activity are below threshold. The previous definition for Low_activity had positive value if EITHER vigorous or moderate activity were below threshold.

#Join the two datasets.
df <- left_join(chd, covariates, by = "Patient_ID")

#Reformat variables to factors, etc.
df <- df %>%
  mutate_at(vars(CHD, CHDsubtype, MetaCategory, Sex, Caucasian, Country, Household_income, Smoking, Alcohol, Weight, Has_FHx_CVD, Low_activity, hypertension_meds, MACEprev:HLDprev, AFIBbeforeSTROKE:HFbeforeAFIB), funs(as.factor)) %>%
    #Relevel reference categories for categorical covariates
  mutate(MetaCategory = relevel(MetaCategory, "CONTROL"),
         CHDsubtype = relevel(CHDsubtype, "CONTROL"),
         Smoking = relevel(Smoking, "Never"),
         Alcohol = relevel(Alcohol, "Seldom"),
         Weight = relevel(Weight, "Non-obese"))
```

```{r sensitivity_data, include = F}
#Load dataset for Sensitivity Analysis B - restricted age criteria for inferred BAV - 55 years of age for AoV replacement and 50 years of age for diagnosis of Ao stenosis or Ao insufficiency.
sensB <- read.csv("../../Datasets/Sensitivity/sensB_5550.csv", sep = ",", header = T) %>%
  mutate(SensB = CHDsubtype)

#Load binary variable indicating occurrence of AoV replacement for Sensitivity Analysis C.
avr <- read.csv("../../Datasets/Sensitivity/patients_with_AoV_replacement.csv", sep = ",", header = T)

#Load cardiac surgery variable indicating occurrence of cardiac surgery before each outcome for Sensitivity Analysis E.
cardiac_surgery <- read.csv("../../Datasets/Cardiac_Surgery_Variables_May10.csv", sep = ",", header = T) %>%
  select(Patient_ID, CS_First_Age, Total_Cardiac_Op)

#Join datasets
df_with_sensitivity <- df %>%
  left_join(select(sensB, Patient_ID, SensB), by = "Patient_ID") %>%
  left_join(avr, by = "Patient_ID") %>%
  left_join(cardiac_surgery, by = "Patient_ID") %>%
  mutate(SensB = ifelse(is.na(SensB), "CONTROL", as.character(SensB))) %>%
  mutate(SensB = as.factor(SensB), SensB = relevel(SensB, "CONTROL"), AVR = as.factor(AVR)) %>%
  mutate(CSbeforeMACE = as.factor(ifelse(!is.na(CS_First_Age) & MACEbin == 1 & MACEtime-CS_First_Age >=0 & MACEtime- CS_First_Age <=1, 1, 0)),
         CSbeforeCAD = as.factor(ifelse(!is.na(CS_First_Age) & CADbin == 1 & CADtime-CS_First_Age >=0 & CADtime- CS_First_Age <=1, 1, 0)),
         CSbeforeACS = as.factor(ifelse(!is.na(CS_First_Age) & ACSbin == 1 & ACStime-CS_First_Age >=0 & ACStime- CS_First_Age <=1, 1, 0)),
         CSbeforeSTROKE = as.factor(ifelse(!is.na(CS_First_Age) & ISC_STROKEbin == 1 & ISC_STROKEtime-CS_First_Age >=0 & ISC_STROKEtime- CS_First_Age <=1, 1, 0)),
         CSbeforeAFIB = as.factor(ifelse(!is.na(CS_First_Age) & AFIBbin == 1 & AFIBtime-CS_First_Age >=0 & AFIBtime- CS_First_Age <=1, 1, 0)),
         CSbeforeHF = as.factor(ifelse(!is.na(CS_First_Age) & HFbin == 1 & HFtime-CS_First_Age >=0 & HFtime- CS_First_Age <=1, 1, 0)))
```

```{r Table1}
#https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html

#Variables for table 1
myvars <- c("Age_baseline", "Sex", "Caucasian", "Townsend", "Smoking", "Alcohol","Weight", "BMI", "Has_FHx_CVD", "BP_systolic_AVG", "BP_diastolic_AVG", "HTNprev", "HLDprev", "DIABETESprev", "Low_activity")
#Table 1 comparing across subtypes of CHD and controls
table1 <- CreateTableOne(data = df_with_sensitivity, vars = myvars, strata = "CHDsubtype")
table1export <- print(table1, showAllLevels = T, nonnormal = T)
#Table 1 comparing CHD to controls
table1_chd <- CreateTableOne(data=df_with_sensitivity, vars = myvars, strata = "CHD")
table1_chdexport <- print(table1_chd, showAllLevels=T, nonnormal=T)
```

```{r cox_assumption_tests, include = F}

##Cox Proportional Hazards assumptions tests for MACE outcome
non_complex <- df_with_sensitivity %>%
  mutate(CHDsubtype = as.character(CHDsubtype)) %>%
  filter(CHDsubtype!="BAV") %>%
  mutate(CHDsubtype = as.factor(CHDsubtype)) %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0)

bav <- df_with_sensitivity %>%
  mutate(CHDsubtype = as.character(CHDsubtype)) %>%
  filter(CHDsubtype!="NON_SEVERE") %>%
  mutate(CHDsubtype = as.factor(CHDsubtype)) %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0)

#########Cox models
mace.cox.ns <- coxph(Surv(MACEtime, MACEbin)~CHD, data = non_complex)
mace.cox.bav <- coxph(Surv(MACEtime, MACEbin)~CHD, data = bav)

########Schoenfeld residuals tests
test.mace.ns <- cox.zph(mace.cox.ns)
test.mace.bav <- cox.zph(mace.cox.bav)

######Log-log survival curve plots
plot(survfit(mace.cox.ns, data.frame(CHD=as.factor(c(0,1)))),
     fun = "cloglog",
     ylab = "loglog",
     lty = c(3,5)) #...Log log plot for non-complex looks parallel

plot(survfit(mace.cox.bav, data.frame(CHD=as.factor(c(0,1)))),
     fun = "cloglog",
     ylab = "loglog",
     lty = c(3,5)) #...Log log plot for bav looks parallel

```

**MACE Outcome**
```{r MACE_models}
##Run cox model for all CHDsubtypes
mace_data <- df_with_sensitivity %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0) 

# mace_data_age <- mace_data %>%
#   mutate(MACEtime = MACEtime + (Age_baseline))
#could use this to display cumulative incidence by age


formulas <- list("All" = 'CHD', "Subtypes" = 'CHDsubtype', "SensitivityA" = 'MetaCategory', "SensitivityB"='SensB')

bindresults <- function(models) {
  results <- data.frame(summary(models[[1]])$conf.int)["CHD1",]
  results <- rbind(results, data.frame(summary(models[[2]])$conf.int)["CHDsubtypeBAV",])
  results <- rbind(results, data.frame(summary(models[[3]])$conf.int)["MetaCategoryINFERRED_BAV",])
  results <- rbind(results, data.frame(summary(models[[4]])$conf.int)["SensBBAV",])
  results <- rbind(results, data.frame(summary(models[[2]])$conf.int)["CHDsubtypeNON_SEVERE",])
  
  pvalues <- data.frame(summary(models[[1]])$coefficients)["CHD1",]
  pvalues <- rbind(pvalues, data.frame(summary(models[[2]])$coefficients)["CHDsubtypeBAV",])
  pvalues <- rbind(pvalues, data.frame(summary(models[[3]])$coefficients)["MetaCategoryINFERRED_BAV",])
  pvalues <- rbind(pvalues, data.frame(summary(models[[4]])$coefficients)["SensBBAV",])
  pvalues <- rbind(pvalues, data.frame(summary(models[[2]])$coefficients)["CHDsubtypeNON_SEVERE",])

  pvalues <- pvalues %>%
    mutate(pvalue = `Pr...z..`) %>%
    select(pvalue)
  results <- results %>%
    select(-`exp..coef.`)
  results <- cbind(results, pvalues)

  return(results)
}

#Unadjusted
macemodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(MACEtime, MACEbin)~',x)), data = mace_data)})

View(bindresults(macemodels))

#Simple adjusted
macemodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(MACEtime, MACEbin)~Age_baseline + Sex + Townsend + Caucasian +',x)), data = mace_data)})

View(bindresults(macemodels))

#Multivariable adjusted
macemodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(MACEtime, MACEbin)~Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev +',x)), data = mace_data)})

View(bindresults(macemodels))

#Sensitivity C - No AoVR replacements
mace_data.noavr <- filter(mace_data, AVR == 0)

mace.noavr <- coxph(Surv(MACEtime, MACEbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev, data = mace_data.noavr)

#Sensitivity D - Exclude non-specific CHD from Non-complex group
#Exclude Heart surgery prior to age 18 (HEART_SURGERY_COND) and unspecified CHD (CHD_UNSPECIFIED)
mace_data.noncom_sens <- filter(mace_data, Malformation != "HEART_SURGERY_COND" & Malformation != "CHD_UNSPECIFIED,")

mace.noncom.sens <- coxph(Surv(MACEtime, MACEbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev, data = mace_data.noncom_sens)

#Sensitivity E - Exclude all participants with any form of cardiac surgery
mace_data.nosurg <- filter(mace_data, CSbeforeMACE == 0)

mace.nosurg <- coxph(Surv(MACEtime, MACEbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev, data = mace_data.nosurg)

```

```{r MACE_unadjustedplot}

mace <- survfit(Surv(MACEtime, MACEbin)~CHDsubtype, data = mace_data)

mace_logrank <- survdiff(Surv(MACEtime, MACEbin)~CHDsubtype, data = mace_data)

mace_plot <- ggsurvplot(mace, title = "MACE", xlab = "Follow-up time (years)", ylab = "Probability of Event-free Survival",
                 xlim = c(0,20), 
                 ylim = c(0,1.00),
                 conf.int = T,
                 font.main = c(24, "bold", "darkblue"),
                 legend = c(0.4,0.2),
                 legend.labs = c("Control (reference)", "Isolated AoV defect (p <0.0001)", "Non-complex defect (p <0.0001)"),
                 font.legend = c(20),
                 font.x = 20,
                 font.y = 20,
                 risk.table = TRUE, 
                 risk.table.col = "strata",
                 risk.table.y.text = F,
                 risk.table.fontsize = 5.2,
                 palette = c("#c71e1d","#3aa28b","#9142bf"))

png("mace_model_062618.png", height = 550, width = 600)
mace_plot
dev.off()


```

```{r MACE_age_adj_risk_stratified}
numrisk = function(data) {
  risk_level = c()
  for (i in 1:nrow(data)) {
    num = 0
    num = ifelse(data$Sex[i] == 1, num +1, num)
    num = ifelse(!is.na(data$Has_FHx_CVD[i]) & data$Has_FHx_CVD[i] == 1, num +1, num)
    num = ifelse(!is.na(data$Smoking[i]) & (data$Smoking[i] == "Current" | data$Smoking[i] == "Previous"), num + 1, num)
    num = ifelse(!is.na(data$Weight[i]) & data$Weight[i] == "Obese", num +1, num)
    num = ifelse(!is.na(data$HTNprev[i]) & data$HTNprev[i] == 1, num + 1, num)
    num = ifelse(!is.na(data$HLDprev[i]) & data$HLDprev[i] == 1, num + 1, num)
    num = ifelse(!is.na(data$DIABETESprev[i]) & data$DIABETESprev[i] == 1, num +1, num)
    num = ifelse(!is.na(data$Low_activity[i]) & data$Low_activity[i] ==1, num +1, num)
    risk_level = append(risk_level, num)
  }
  return(risk_level)
}

df_with_sens_and_risklevels <- df_with_sensitivity %>%
  mutate(risk_level8 = numrisk(df_with_sensitivity))
  
df_with_sens_and_risklevels$risk8tertiles <- quantcut(df_with_sens_and_risklevels$risk_level8, 3)
#df_with_sens_and_risk_levels is saved as Paper1_df_sensitivity_and_risklevels_June14.csv and uses "alternative" definition of Low_activity (both vigorous and moderate activity levels must be below threshold for Low_activity == 1).

low_risk <- filter(df_with_sens_and_risklevels, risk_level8 <=2)
int_risk <- filter(df_with_sens_and_risklevels, risk_level8 >2 & risk_level8 <=4)
high_risk <- filter(df_with_sens_and_risklevels, risk_level8 >=5)

mace_low <- low_risk %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0) 
mace_int <- int_risk %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0) 
mace_high <- high_risk %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0) 

MACE_low_risk <- coxph(Surv(MACEtime, MACEbin) ~ CHDsubtype + Age_baseline + Caucasian + Townsend, data = mace_low)

MACE_int_risk <- coxph(Surv(MACEtime, MACEbin) ~ CHDsubtype + Age_baseline + Caucasian + Townsend, data = mace_int)

MACE_high_risk <- coxph(Surv(MACEtime, MACEbin) ~ CHDsubtype + Age_baseline + Caucasian + Townsend, data = mace_high)

########Forest plots#########
library(forestplot)

unad <- coxph(Surv(MACEtime, MACEbin)~CHDsubtype, data = mace_data)
cvmodels <- list("Low Risk"=MACE_low_risk,"Int Risk" = MACE_int_risk, "High Risk"=MACE_high_risk)
cvsummaries <- lapply(cvmodels, summary)

res_table <- function(model_summaries) {
  results_matrix <- matrix(nrow = 2, ncol = 12, dimnames = list(c("Isolated AoV Defect", "Non-complex Defect"), c("Low_HR","Low_Lower", "Low_Upper","Low_p","Int_HR","Int_Lower","Int_Upper","Int_p", "High_HR", "High_Lower", "High_Upper", "High_p")))
  for (i in 1:2) {
    results_matrix[i,1] = model_summaries[[1]]$conf.int[[i]]
    results_matrix[i,2] = model_summaries[[1]]$conf.int[[i+10]]
    results_matrix[i,3] = model_summaries[[1]]$conf.int[[i+15]]
    results_matrix[i,4] = model_summaries[[1]]$coefficients[[i+20]]
    results_matrix[i,5] = model_summaries[[2]]$conf.int[[i]]
    results_matrix[i,6] = model_summaries[[2]]$conf.int[[i+10]]
    results_matrix[i,7] = model_summaries[[2]]$conf.int[[i+15]]
    results_matrix[i,8] = model_summaries[[2]]$coefficients[[i+20]]
    results_matrix[i,9] = model_summaries[[3]]$conf.int[[i]]
    results_matrix[i,10] = model_summaries[[3]]$conf.int[[i+10]]
    results_matrix[i,11] = model_summaries[[3]]$conf.int[[i+15]]
    results_matrix[i,12] = model_summaries[[3]]$coefficients[[i+20]]
  }
  return(results_matrix)
}

cvresults <- res_table(cvsummaries)

cvresults_df <- as.data.frame(cvresults) %>%
  mutate(Low = paste0(round(Low_HR,1)," (",round(Low_Lower,1),"-",round(Low_Upper,1),")"),
         Int = paste0(round(Int_HR,1)," (",round(Int_Lower,1),"-",round(Int_Upper,1),")"),
         High = paste0(round(High_HR,1)," (",round(High_Lower,1),"-",round(High_Upper,1),")"))

cvresults_df <- rbind(c(rep(c(1.0, 1, 1, "Reference"), 3), rep("1.0", 3)), cvresults_df)
cvresults_df <- mutate_at(cvresults_df, vars(Low_HR:Low_Upper, Int_HR:Int_Upper, High_HR:High_Upper), funs(as.numeric))


cvtabletext <- cbind(c(NA,"<=2 CV Risk Factors","Control (No ACHD)",rownames(cvresults),
                       "3-4 CV Risk Factors","Control (No ACHD)",rownames(cvresults),
                       ">=5 CV Risk Factors","Control (No ACHD)",rownames(cvresults)),
                     c("No. Events/No. at Risk",NA,"4,739/183,464","53/159","74/282",NA,"15,756/224,841","191/469","191/412",NA,"16,929/82,881","232/390","110/188"),
                     c("HR (95% CI)",NA,cvresults_df$Low,NA,cvresults_df$Int,NA,cvresults_df$High),
                     c("P value",NA,"Reference",rep("<0.001",2),NA,"Reference",rep("<0.001",2),NA,"Reference",rep("<0.001",2)))

png("mace_forest_111518.png", height = 1000, width = 1200)

forestplot(cvtabletext,
           mean = c(NA,NA,cvresults_df$Low_HR,NA,cvresults_df$Int_HR,NA,cvresults_df$High_HR),
           lower = c(NA,NA,cvresults_df$Low_Lower,NA,cvresults_df$Int_Lower,NA,cvresults_df$High_Lower),
           upper = c(NA,NA,cvresults_df$Low_Upper,NA,cvresults_df$Int_Upper,NA,cvresults_df$High_Upper),
           clip = c(-.1, 25),
           hrzl_lines = list("2" = gpar(lwd=1, columns=1:4, col = "black")),
           graph.pos = 3,
           txt_gp = fpTxtGp(label = gpar(fontfamily = "Arial", cex = 1),
                            xlab = gpar(fontfamily = "Arial", cex = 5)),
           col = fpColors(box = "darkblue", line = "darkblue"),
           boxsize = 0.2,
           fn.ci_norm = fpDrawDiamondCI,
           lty.ci = 1,
           ci.vertices.height = 0.04,
           colgap = unit(1, "mm"),
           graphwidth = unit(8, "cm"),
           lineheight = unit(1.0, "cm"))

dev.off()

```

```{r age_adjusted_incidence_bar_plot_for_MACE}
library(epiR)
df_with_sens_and_risklevels <- df_with_sens_and_risklevels %>%
  mutate(risk_stratum = ifelse(risk_level8 <=2, "low",
                               ifelse(risk_level8 >=5, "high", "int")),
         age_stratum = ifelse(Age_baseline < 50, "50",
                              ifelse(Age_baseline >60, "60", "50_60")))


##########MACE########
mace_df <- df_with_sens_and_risklevels %>%
  mutate(MACEtime = MACEtime - (Age_baseline-10)) %>%
  filter(MACEtime >=0)

###Data preparation/calculations done in Excel file.
#obs = a one column matrix representing the number of observed number of events in each strata. The dimensions of obs must be named (see the examples, below)
obs <- matrix(data = c(4168,
                       47,
                       70,
                       13566,
                       168,
                       168,
                       13251,
                       191,
                       90), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"), ""))


#pop = a matrix representing population size. Rows represent strata (e.g. region); columns represent the levels of the covariate to be adjusted for (e.g. age class, gender). The sum of each row will equal the total population size within each stratum. If there are no covariates pop will be a one column matrix. The dimen- sions of the pop matrix must be named (see the examples, below).
pop <- matrix(data = c(58518,71238,54983,
                       38,80,48,
                       103,124,76,
                       48543,88096,91472,
                       74,222,196,
                       101,163,162,
                       10079,30596,44458,
                       35,164,225,
                       34,70,91), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"),
                              c("<50","50-60",">60")))


#std = a one row matrix specifying the standard incidence risks to be applied to each level of the covariate to be adjusted for. The length of std should be one plus the number of covariates to be adjusted for (the additional value represents the incidence risk in the entire population). If there are no covariates to adjust for std is a single number representing the incidence risk in the entire population.
std <- matrix(data = c(0.018907851,
                       0.051007967,
                       0.109263879,
                       0.065194335), nrow = 1, byrow = TRUE,
              dimnames = list("", c("<50", "50-60", ">60","Total")))

age_ad_incidence_rate <- epi.indirectadj(obs = obs, pop = pop, std = std, units = 100, conf.level = 0.95)
IAR <- age_ad_incidence_rate$adj.strata
IAR$RiskLevel <- c(rep("High",3),rep("Intermediate",3),rep("Low",3))
IAR$Group <- c(rep(c("Isolated AoV Defect","Control","Non-complex Defect"),3))
IAR <- select(IAR, RiskLevel, Group, est, lower, upper)
print(levels(factor(IAR$RiskLevel)))
IAR$RiskLevel = factor(IAR$RiskLevel, levels(factor(IAR$RiskLevel))[c(3,2,1)])

mace_fig <- ggplot(IAR, aes(RiskLevel, est, fill = Group)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin=lower, ymax = upper),
                width = 0.2,
                position = position_dodge(0.9)) +
  scale_fill_manual("", values = c("#c71e1d","#3aa28b","#9142bf")) +
  ggtitle("20-year Standardized Event Rate for MACE") +
  xlab("Number of Cardiovascular Risk Factors") +
  ylab("Age-adjusted 20-year Event Rate (%)") + 
  theme(legend.text = element_text(size = 14), axis.text = element_text(size = 12))

png("incidence_mace_fig.png", height = 600, width = 750)
mace_fig
dev.off()

```

```{r acs_bar_plot}
##########MACE########
acs_df <- df_with_sens_and_risklevels %>%
  mutate(ACStime = ACStime - (Age_baseline-10)) %>%
  filter(ACStime >=0)

###Data preparation/calculations done in Excel file.
#obs = a one column matrix representing the number of observed number of events in each strata. The dimensions of obs must be named (see the examples, below)
obs <- matrix(data = c(985,
                       7,
                       9,
                       4848,
                       38,
                       40,
                       6664,
                       81,
                       24), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"), ""))


#pop = a matrix representing population size. Rows represent strata (e.g. region); columns represent the levels of the covariate to be adjusted for (e.g. age class, gender). The sum of each row will equal the total population size within each stratum. If there are no covariates pop will be a one column matrix. The dimen- sions of the pop matrix must be named (see the examples, below).
pop <- matrix(data = c(58518,71238,54983,
                       38,80,48,
                       103,124,76,
                       48543,88096,91472,
                       74,222,196,
                       101,163,162,
                       10079,30596,44458,
                       35,164,225,
                       34,70,91), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"),
                              c("<50","50-60",">60")))


#std = a one row matrix specifying the standard incidence risks to be applied to each level of the covariate to be adjusted for. The length of std should be one plus the number of covariates to be adjusted for (the additional value represents the incidence risk in the entire population). If there are no covariates to adjust for std is a single number representing the incidence risk in the entire population.
std <- matrix(data = c(0.008362274,
                       0.022016406,
                       0.040445998,
                       0.025754625), nrow = 1, byrow = TRUE,
              dimnames = list("", c("<50", "50-60", ">60","Total")))

age_ad_incidence_rate <- epi.indirectadj(obs = obs, pop = pop, std = std, units = 100, conf.level = 0.95)
IAR <- age_ad_incidence_rate$adj.strata
IAR$RiskLevel <- c(rep("High",3),rep("Intermediate",3),rep("Low",3))
IAR$Group <- c(rep(c("Isolated AoV Defect","Control","Non-complex Defect"),3))
IAR <- select(IAR, RiskLevel, Group, est, lower, upper)
print(levels(factor(IAR$RiskLevel)))
IAR$RiskLevel = factor(IAR$RiskLevel, levels(factor(IAR$RiskLevel))[c(3,2,1)])

acs_fig <- ggplot(IAR, aes(RiskLevel, est, fill = Group)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin=lower, ymax = upper),
                width = 0.2,
                position = position_dodge(0.9)) +
  scale_fill_manual("", values = c("#c71e1d","#3aa28b","#9142bf")) +
  ylim(0, 30) +
  ggtitle("20-year Standardized Event Rate for ACS") +
  xlab("Number of Cardiovascular Risk Factors") +
  ylab("Age-adjusted 20-year Event Rate (%)") + 
  theme(legend.text = element_text(size = 14), axis.text = element_text(size = 12))
```

```{r stroke_bar_plot}
##########MACE########
stroke_df <- df_with_sens_and_risklevels %>%
  mutate(ISC_STROKEtime = ISC_STROKEtime - (Age_baseline-10)) %>%
  filter(ISC_STROKEtime >=0)

###Data preparation/calculations done in Excel file.
#obs = a one column matrix representing the number of observed number of events in each strata. The dimensions of obs must be named (see the examples, below)
obs <- matrix(data = c(1174,
                       7,
                       17,
                       4038,
                       37,
                       44,
                       3886,
                       45,
                       25), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"), ""))


#pop = a matrix representing population size. Rows represent strata (e.g. region); columns represent the levels of the covariate to be adjusted for (e.g. age class, gender). The sum of each row will equal the total population size within each stratum. If there are no covariates pop will be a one column matrix. The dimen- sions of the pop matrix must be named (see the examples, below).
pop <- matrix(data = c(58518,71238,54983,
                       38,80,48,
                       103,124,76,
                       48543,88096,91472,
                       74,222,196,
                       101,163,162,
                       10079,30596,44458,
                       35,164,225,
                       34,70,91), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"),
                              c("<50","50-60",">60")))


#std = a one row matrix specifying the standard incidence risks to be applied to each level of the covariate to be adjusted for. The length of std should be one plus the number of covariates to be adjusted for (the additional value represents the incidence risk in the entire population). If there are no covariates to adjust for std is a single number representing the incidence risk in the entire population.
std <- matrix(data = c(0.005508702,
                       0.014399452,
                       0.03114962,
                       0.01868769), nrow = 1, byrow = TRUE,
              dimnames = list("", c("<50", "50-60", ">60","Total")))

age_ad_incidence_rate <- epi.indirectadj(obs = obs, pop = pop, std = std, units = 100, conf.level = 0.95)
IAR <- age_ad_incidence_rate$adj.strata
IAR$RiskLevel <- c(rep("High",3),rep("Intermediate",3),rep("Low",3))
IAR$Group <- c(rep(c("Isolated AoV Defect","Control","Non-complex Defect"),3))
IAR <- select(IAR, RiskLevel, Group, est, lower, upper)
print(levels(factor(IAR$RiskLevel)))
IAR$RiskLevel = factor(IAR$RiskLevel, levels(factor(IAR$RiskLevel))[c(3,2,1)])

stroke_fig <- ggplot(IAR, aes(RiskLevel, est, fill = Group)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin=lower, ymax = upper),
                width = 0.2,
                position = position_dodge(0.9)) +
  scale_fill_manual("", values = c("#c71e1d","#3aa28b","#9142bf")) +
  ylim(0,30) +
  ggtitle("20-year Standardized Event Rate for Ischemic Stroke") +
  xlab("Number of Cardiovascular Risk Factors") +
  ylab("Age-adjusted 20-year Event Rate (%)") + 
  theme(legend.text = element_text(size = 14), axis.text = element_text(size = 12))
```

```{r hf_bar_plot}
##########MACE########
hf_df <- df_with_sens_and_risklevels %>%
  mutate(HFtime = HFtime - (Age_baseline-10)) %>%
  filter(HFtime >=0)

###Data preparation/calculations done in Excel file.
#obs = a one column matrix representing the number of observed number of events in each strata. The dimensions of obs must be named (see the examples, below)
obs <- matrix(data = c(462,
                       15,
                       10,
                       1519,
                       52,
                       44,
                       2217,
                       66,
                       40), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"), ""))


#pop = a matrix representing population size. Rows represent strata (e.g. region); columns represent the levels of the covariate to be adjusted for (e.g. age class, gender). The sum of each row will equal the total population size within each stratum. If there are no covariates pop will be a one column matrix. The dimen- sions of the pop matrix must be named (see the examples, below).
pop <- matrix(data = c(58518,71238,54983,
                       38,80,48,
                       103,124,76,
                       48543,88096,91472,
                       74,222,196,
                       101,163,162,
                       10079,30596,44458,
                       35,164,225,
                       34,70,91), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"),
                              c("<50","50-60",">60")))


#std = a one row matrix specifying the standard incidence risks to be applied to each level of the covariate to be adjusted for. The length of std should be one plus the number of covariates to be adjusted for (the additional value represents the incidence risk in the entire population). If there are no covariates to adjust for std is a single number representing the incidence risk in the entire population.
std <- matrix(data = c(0.002018275,
                       0.006139032,
                       0.015863844,
                       0.008884561), nrow = 1, byrow = TRUE,
              dimnames = list("", c("<50", "50-60", ">60","Total")))

age_ad_incidence_rate <- epi.indirectadj(obs = obs, pop = pop, std = std, units = 100, conf.level = 0.95)
IAR <- age_ad_incidence_rate$adj.strata
IAR$RiskLevel <- c(rep("High",3),rep("Intermediate",3),rep("Low",3))
IAR$Group <- c(rep(c("Isolated AoV Defect","Control","Non-complex Defect"),3))
IAR <- select(IAR, RiskLevel, Group, est, lower, upper)
print(levels(factor(IAR$RiskLevel)))
IAR$RiskLevel = factor(IAR$RiskLevel, levels(factor(IAR$RiskLevel))[c(3,2,1)])

hf_fig <- ggplot(IAR, aes(RiskLevel, est, fill = Group)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin=lower, ymax = upper),
                width = 0.2,
                position = position_dodge(0.9)) +
  scale_fill_manual("", values = c("#c71e1d","#3aa28b","#9142bf")) +
  ylim(0,30) +
  ggtitle("20-year Standardized Event Rate for Heart Failure") +
  xlab("Number of Cardiovascular Risk Factors") +
  ylab("Age-adjusted 20-year Event Rate (%)") + 
  theme(legend.text = element_text(size = 14), axis.text = element_text(size = 12))
```

```{r afib_bar_plot}
##########MACE########
afib_df <- df_with_sens_and_risklevels %>%
  mutate(AFIBtime = AFIBtime - (Age_baseline-10)) %>%
  filter(AFIBtime >=0)

###Data preparation/calculations done in Excel file.
#obs = a one column matrix representing the number of observed number of events in each strata. The dimensions of obs must be named (see the examples, below)
obs <- matrix(data = c(2115,
                       35,
                       50,
                       5598,
                       108,
                       114,
                       4819,
                       105,
                       58), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"), ""))


#pop = a matrix representing population size. Rows represent strata (e.g. region); columns represent the levels of the covariate to be adjusted for (e.g. age class, gender). The sum of each row will equal the total population size within each stratum. If there are no covariates pop will be a one column matrix. The dimen- sions of the pop matrix must be named (see the examples, below).
pop <- matrix(data = c(58518,71238,54983,
                       38,80,48,
                       103,124,76,
                       48543,88096,91472,
                       74,222,196,
                       101,163,162,
                       10079,30596,44458,
                       35,164,225,
                       34,70,91), nrow = 9, byrow = TRUE,
              dimnames = list(c("L.controls",
                                "L.AV",
                                "L.NS",
                                "I.controls",
                                "I.AV",
                                "I.NS",
                                "H.controls",
                                "H.AV",
                                "H.NS"),
                              c("<50","50-60",">60")))


#std = a one row matrix specifying the standard incidence risks to be applied to each level of the covariate to be adjusted for. The length of std should be one plus the number of covariates to be adjusted for (the additional value represents the incidence risk in the entire population). If there are no covariates to adjust for std is a single number representing the incidence risk in the entire population.
std <- matrix(data = c(0.005108263,
                       0.017148614,
                       0.048469185,
                       0.026231691), nrow = 1, byrow = TRUE,
              dimnames = list("", c("<50", "50-60", ">60","Total")))

age_ad_incidence_rate <- epi.indirectadj(obs = obs, pop = pop, std = std, units = 100, conf.level = 0.95)
IAR <- age_ad_incidence_rate$adj.strata
IAR$RiskLevel <- c(rep("High",3),rep("Intermediate",3),rep("Low",3))
IAR$Group <- c(rep(c("Isolated AoV Defect","Control","Non-complex Defect"),3))
IAR <- select(IAR, RiskLevel, Group, est, lower, upper)
print(levels(factor(IAR$RiskLevel)))
IAR$RiskLevel = factor(IAR$RiskLevel, levels(factor(IAR$RiskLevel))[c(3,2,1)])

afib_fig <- ggplot(IAR, aes(RiskLevel, est, fill = Group)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin=lower, ymax = upper),
                width = 0.2,
                position = position_dodge(0.9)) +
  scale_fill_manual("", values = c("#c71e1d","#3aa28b","#9142bf")) +
  ylim(0,30) +
  ggtitle("20-year Standardized Event Rate for Atrial Fibrillation") +
  xlab("Number of Cardiovascular Risk Factors") +
  ylab("Age-adjusted 20-year Event Rate (%)") + 
  theme(legend.text = element_text(size = 14), axis.text = element_text(size = 12))
```

```{r incidence_plots}

png("incidence_supp_fig.png", height = 1200, width = 1500)
multiplot(acs_fig, stroke_fig, hf_fig, afib_fig, cols = 2)
dev.off()
```

```{r interaction_tests, include=F}
mace_data_modified <- mace_data %>%
  mutate(Smoking = as.character(Smoking)) %>%
  mutate(Smoking = ifelse(Smoking == "Current" | Smoking == "Previous", "Current/former", Smoking)) %>%
  mutate(Smoking = as.factor(Smoking), Smoking = relevel(Smoking, ref = "Never"))

interact_vars <- c("Sex","Smoking","Weight","Has_FHx_CVD","HTNprev","HLDprev","DIABETESprev","Low_activity")

MACE_interact_models <- lapply(interact_vars, function(x){summary(coxph(as.formula(paste('Surv(MACEtime, MACEbin)~CHDsubtype+', x,'+CHDsubtype*',x)), data = mace_data_modified))})

interact_table <- function(result_summaries) {
  results_matrix <- matrix(nrow = length(result_summaries), ncol = 4, dimnames = list(interact_vars, c("Isolated AV defect_coef","Isolated AV defect_p", "Non-complex CHD_coef", "Non-severe CHD_p")))
  for (i in 1:nrow(results_matrix)) {
    results_matrix[i,1] = result_summaries[[i]]$coefficients[[4]]
    results_matrix[i,2] = result_summaries[[i]]$coefficients[[24]]
    results_matrix[i,3] = result_summaries[[i]]$coefficients[[5]]
    results_matrix[i,4] = result_summaries[[i]]$coefficients[[25]]
  }
  return(results_matrix)
}

MACE_interact <- interact_table(MACE_interact_models)

```

**Individual CV Outcomes**
```{r individual_CV_outcomes_cox_assumption_tests}
###Follow up from 10 years prior to enrollment to current timepoint.
acs.ns40 <- non_complex %>%
  mutate(CADtime = CADtime - (Age_baseline-10)) %>%
  filter(CADtime >=0)

stroke.ns40 <- non_complex %>%
  mutate(ISC_STROKEtime = ISC_STROKEtime - (Age_baseline-10)) %>%
  filter(ISC_STROKEtime >=0)

hf.ns40 <- non_complex %>%
  mutate(HFtime = HFtime - (Age_baseline-10)) %>%
  filter(HFtime >=0)

afib.ns40 <- non_complex %>%
  mutate(AFIBtime = AFIBtime - (Age_baseline-10)) %>%
  filter(AFIBtime >=0)

acs.cox.ns40 <- coxph(Surv(CADtime, CADbin)~CHD, data = acs.ns40)
stroke.cox.ns40 <- coxph(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHD, data = stroke.ns40)
hf.cox.ns40 <- coxph(Surv(HFtime, HFbin)~CHD, data = hf.ns40)
afib.cox.ns40 <- coxph(Surv(AFIBtime, AFIBbin)~CHD, data = afib.ns40)

test.acs.ns40 <- cox.zph(acs.cox.ns40)
test.stroke.ns40 <- cox.zph(stroke.cox.ns40)
test.hf.ns40 <- cox.zph(hf.cox.ns40)
test.afib.ns40 <- cox.zph(afib.cox.ns40)

acs.bav40 <- bav %>%
  mutate(CADtime = CADtime - (Age_baseline-10)) %>%
  filter(CADtime >=0)

stroke.bav40 <- bav %>%
  mutate(ISC_STROKEtime = ISC_STROKEtime - (Age_baseline-10)) %>%
  filter(ISC_STROKEtime >=0)

hf.bav40 <- bav %>%
  mutate(HFtime = HFtime - (Age_baseline-10)) %>%
  filter(HFtime >=0)

afib.bav40 <- bav %>%
  mutate(AFIBtime = AFIBtime - (Age_baseline-10)) %>%
  filter(AFIBtime >=0)

acs.cox.bav40 <- coxph(Surv(CADtime, CADbin)~CHDsubtype, data = acs.bav40)
stroke.cox.bav40 <- coxph(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHDsubtype, data = stroke.bav40)
hf.cox.bav40 <- coxph(Surv(HFtime, HFbin)~CHDsubtype, data = hf.bav40)
afib.cox.bav40 <- coxph(Surv(AFIBtime, AFIBbin)~CHDsubtype, data = afib.bav40)

test.acs.bav40 <- cox.zph(acs.cox.bav40)
test.stroke.bav40 <- cox.zph(stroke.cox.bav40)
test.hf.bav40 <- cox.zph(hf.cox.bav40)
test.afib.bav40 <- cox.zph(afib.cox.bav40)

```

*Acute Coronary Syndrome*
```{r ACS_models}
####adjusted follow up window
acs_data <- df_with_sensitivity %>%
  mutate(ACStime = ACStime - (Age_baseline-10)) %>%
  filter(ACStime >=0)

#Unadjusted
acs_models <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(ACStime, ACSbin)~',x)), data = acs_data)})

View(bindresults(acs_models))

#Simple adjusted
acs_models <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(ACStime, ACSbin)~Age_baseline + Sex + Townsend + Caucasian +',x)), data = acs_data)})

View(bindresults(acs_models))

#Multivariable adjusted
acs_models <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(ACStime, ACSbin)~Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeACS +',x)), data = acs_data)})

View(bindresults(acs_models))

##Sensitivity C - no AVR

acs_data.noavr <- filter(acs_data, AVR == 0)

acs.noavr <- coxph(Surv(ACStime, ACSbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeACS, data = acs_data.noavr)

##Sensitivity D - no unspecified CHD in non-complex group
acs_data.noncom_sens <- filter(acs_data, Malformation != "HEART_SURGERY_COND" & Malformation != "CHD_UNSPECIFIED,")

acs.noncom.sens <- coxph(Surv(ACStime, ACSbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeACS, data = acs_data.noncom_sens)

#Sensitivity E - Exclude all participants with any form of cardiac surgery
acs_data.nosurg <- filter(acs_data, CSbeforeACS == 0)

acs.nosurg <- coxph(Surv(ACStime, ACSbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeACS, data = acs_data.nosurg)

```

*Coronary Artery Disease*
```{r CAD_models}
####adjusted follow up window
cad_data <- df_with_sensitivity %>%
  mutate(CADtime = CADtime - (Age_baseline-10)) %>%
  filter(CADtime >=0)

#Unadjusted
cadmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(CADtime, CADbin)~',x)), data = cad_data)})

View(bindresults(cadmodels))

#Simple adjusted
cadmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(CADtime, CADbin)~Age_baseline + Sex + Townsend + Caucasian +',x)), data = cad_data)})

View(bindresults(cadmodels))

#Multivariable adjusted
cadmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(CADtime, CADbin)~Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeCAD +',x)), data = cad_data)})

View(bindresults(cadmodels))

##Sensitivity C - no AVR

cad_data.noavr <- filter(cad_data, AVR == 0)

cad.noavr <- coxph(Surv(CADtime, CADbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeCAD, data = cad_data.noavr)


##Sensitivity D - no unspecified CHD in non-complex group
cad_data.noncom_sens <- filter(cad_data, Malformation != "HEART_SURGERY_COND" & Malformation != "CHD_UNSPECIFIED,")

cad.noncom.sens <- coxph(Surv(CADtime, CADbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeCAD, data = cad_data.noncom_sens)

#Sensitivity E - Exclude all participants with any form of cardiac surgery
cad_data.nosurg <- filter(cad_data, CSbeforeCAD == 0)

cad.nosurg <- coxph(Surv(CADtime, CADbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeCAD, data = cad_data.nosurg)

```

*Ischemic Stroke*
```{r stroke_models}
####adjusted follow up window
stroke_data <- df_with_sensitivity %>%
  mutate(ISC_STROKEtime = ISC_STROKEtime - (Age_baseline-10)) %>%
  filter(ISC_STROKEtime >=0) 

#Unadjusted
strokemodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(ISC_STROKEtime, ISC_STROKEbin)~',x)), data = stroke_data)})

View(bindresults(strokemodels))

#Simple adjusted
strokemodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(ISC_STROKEtime, ISC_STROKEbin)~Age_baseline + Sex + Townsend + Caucasian +',x)), data = stroke_data)})

View(bindresults(strokemodels))

#Multivariate adjusted
strokemodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(ISC_STROKEtime, ISC_STROKEbin)~Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeSTROKE +',x)), data = stroke_data)})

View(bindresults(strokemodels))

#Sensitivity C - no AVR
stroke_data.noavr <- filter(stroke_data, AVR == 0)

stroke.noavr <- coxph(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeSTROKE, data = stroke_data.noavr)

#Sensitivity D - no unspecified non-complex CHD
stroke_data.noncom_sens <- filter(stroke_data, Malformation != "HEART_SURGERY_COND" & Malformation != "CHD_UNSPECIFIED,")

stroke.noncom.sens <- coxph(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeSTROKE, data = stroke_data.noncom_sens)

#Sensitivity E - Exclude all participants with any form of cardiac surgery occurring prior to event
stroke_data.nosurg <- filter(stroke_data, CSbeforeSTROKE == 0)

stroke.nosurg <- coxph(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + AFIBbeforeSTROKE, data = stroke_data.nosurg)

```

*Heart Failure*
```{r hf_models}
####adjusted follow up window
hf_data <- df_with_sensitivity %>%
  mutate(HFtime = HFtime - (Age_baseline-10)) %>%
  filter(HFtime >=0)

#Unadjusted
hfmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(HFtime, HFbin)~',x)), data = hf_data)})

View(bindresults(hfmodels))

#Simple adjusted
hfmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(HFtime, HFbin)~Age_baseline + Sex + Townsend + Caucasian +',x)), data = hf_data)})

View(bindresults(hfmodels))

#Multivariable adjusted
hfmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(HFtime, HFbin)~Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeHF + AFIBbeforeHF +',x)), data = hf_data)})

View(bindresults(hfmodels))


#Sensitivity C - no AVR
hf_data.noavr <- filter(hf_data, AVR == 0)

hf.noavr <- coxph(Surv(HFtime, HFbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeHF + AFIBbeforeHF, data = hf_data.noavr)


#Sensitivity D - no unspecified non-complex CHD
hf_data.noncom_sens <- filter(hf_data, Malformation != "HEART_SURGERY_COND" & Malformation != "CHD_UNSPECIFIED,")

hf.noncom.sens <- coxph(Surv(HFtime, HFbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeHF + AFIBbeforeHF, data = hf_data.noncom_sens)

#Sensitivity E - Exclude all participants with any form of cardiac surgery occurring prior to event
hf_data.nosurg <- filter(hf_data, CSbeforeHF == 0)

hf.nosurg <- coxph(Surv(HFtime, HFbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeHF + AFIBbeforeHF, data = hf_data.nosurg)

```

*Atrial Fibrillation*
```{r afib_models}
####adjusted follow up window
afib_data <- df_with_sensitivity %>%
  mutate(AFIBtime = AFIBtime - (Age_baseline-10)) %>%
  filter(AFIBtime >=0)

#Unadjusted
afibmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(AFIBtime, AFIBbin)~',x)), data = afib_data)})

View(bindresults(afibmodels))

#Simple adjusted
afibmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(AFIBtime, AFIBbin)~ Age_baseline + Sex + Townsend + Caucasian +',x)), data = afib_data)})

View(bindresults(afibmodels))

#Multivariable adjusted
afibmodels <- lapply(formulas, function(x){coxph(as.formula(paste('Surv(AFIBtime, AFIBbin)~Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeAFIB + HFbeforeAFIB +',x)), data = afib_data)})

View(bindresults(afibmodels))

#Sensitivity C - no AVR
afib_data.noavr <- filter(afib_data, AVR == 0)

afib.noavr <- coxph(Surv(AFIBtime, AFIBbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeAFIB + HFbeforeAFIB, data = afib_data.noavr)

#Sensitivity D - no unspecified non-complex CHD
afib_data.noncom_sens <- filter(afib_data, Malformation != "HEART_SURGERY_COND" & Malformation != "CHD_UNSPECIFIED,")

afib.noncom.sens <- coxph(Surv(AFIBtime, AFIBbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeAFIB + HFbeforeAFIB, data = afib_data.noncom_sens)

#Sensitivity E - Exclude all participants with any form of cardiac surgery occurring prior to event
afib_data.nosurg <- filter(afib_data, CSbeforeAFIB == 0)

afib.nosurg <- coxph(Surv(AFIBtime, AFIBbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev + CADbeforeAFIB + HFbeforeAFIB, data = afib_data.nosurg)

```

```{r individual_CV_outcomes_plots}
cad_plot <- survfit(Surv(CADtime, CADbin)~CHDsubtype, data = cad_data)
stroke_plot <- survfit(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHDsubtype, data = stroke_data)
hf_plot <- survfit(Surv(HFtime, HFbin)~CHDsubtype, data = hf_data)
afib_plot <- survfit(Surv(AFIBtime, AFIBbin)~CHDsubtype, data = afib_data)

survdiff(Surv(CADtime, CADbin)~CHDsubtype, data = cad_data)
survdiff(Surv(ISC_STROKEtime, ISC_STROKEbin)~CHDsubtype, data = stroke_data)
survdiff(Surv(HFtime, HFbin)~CHDsubtype, data = hf_data)
survdiff(Surv(AFIBtime, AFIBbin)~CHDsubtype, data = afib_data)


CAD <- ggsurvplot(cad_plot, title = "Acute Coronary Artery Disease", xlab = "Follow-up time (years)", ylab = "Probability of Event-free Survival",
                 xlim = c(0,20), 
                 ylim = c(0.60,1.00),
                 conf.int = T,
                 font.main = c(24, "bold", "darkblue"),
                 legend = c(0.4,0.2),
                 legend.labs = c("Control (reference)", "Isolated AoV defect (p <0.0001)", "Non-complex defect (p <0.0001)"),
                 font.legend = c(20),
                 font.x = 20,
                 font.y = 20,
                 risk.table = TRUE, 
                 risk.table.col = "strata",
                 risk.table.y.text = F,
                 risk.table.fontsize = 5.2,
                 palette = c("#c71e1d","#3aa28b","#9142bf"))

STROKE <- ggsurvplot(stroke_plot, title = "Ischemic Stroke", xlab = "Follow-up time (years)", ylab = "Probability of Event-free Survival",
                 xlim = c(0,20), 
                 ylim = c(0.60,1.00),
                 conf.int = T,
                 font.main = c(24, "bold", "darkblue"),
                 legend = c(0.4,0.2),
                 legend.labs = c("Control (reference)", "Isolated AoV defect (p <0.0001)", "Non-complex defect (p <0.0001)"),
                 font.legend = c(20),
                 font.x = 20,
                 font.y = 20,
                 risk.table = TRUE, 
                 risk.table.col = "strata",
                 risk.table.y.text = F,
                 risk.table.fontsize = 5.2,
                 palette = c("#c71e1d","#3aa28b","#9142bf"))

HF <- ggsurvplot(hf_plot, title = "Heart Failure", xlab = "Follow-up time (years)", ylab = "Probability of Event-free Survival",
                 xlim = c(0,20), 
                 ylim = c(0.60,1.00),
                 conf.int = T,
                 font.main = c(24, "bold", "darkblue"),
                 legend = c(0.4,0.2),
                 legend.labs = c("Control (reference)", "Isolated AoV defect (p <0.0001)", "Non-complex defect (p <0.0001)"),
                 font.legend = c(20),
                 font.x = 20,
                 font.y = 20,
                 risk.table = TRUE, 
                 risk.table.col = "strata",
                 risk.table.y.text = F,
                 risk.table.fontsize = 5.2,
                 palette = c("#c71e1d","#3aa28b","#9142bf"))

AFIB <- ggsurvplot(afib_plot, title = "Atrial Fibrillation", xlab = "Follow-up time (years)", ylab = "Probability of Event-free Survival",
                 xlim = c(0,20), 
                 ylim = c(0.60,1.00),
                 conf.int = T,
                 font.main = c(24, "bold", "darkblue"),
                 legend = c(0.4,0.2),
                 legend.labs = c("Control (reference)", "Isolated AoV defect (p <0.0001)", "Non-complex defect (p <0.0001)"),
                 font.legend = c(20),
                 font.x = 20,
                 font.y = 20,
                 risk.table = TRUE, 
                 risk.table.col = "strata",
                 risk.table.y.text = F,
                 risk.table.fontsize = 5.2,
                 palette = c("#c71e1d","#3aa28b","#9142bf"))

plots <- list(CAD, HF, STROKE, AFIB)
png("univariate_models_062618.png", height = 1100, width = 1200)
arranged <- arrange_ggsurvplots(plots, ncol = 2, nrow = 2, surv.plot.height = 0.8, risk.table.height = 0.2)
dev.off()
```

```{r FPR_BAV_curve}

empiric_fpr <- data.frame("Age" = c(30, 40, 50, 60, 70, 80, 90, 100), "Congenital" = c(6,21,65,148,311,465,503,504), "Normal" = c(0,0,2,27,120,318,416,417)) #Numbers from Roberts and Ko paper.

empiric_fpr <- empiric_fpr %>%
  mutate(FPR = Normal/(Congenital + Normal)) #False positive rate

avr_age <- read.csv("../../Datasets/AOV_REPLACEMENT_Ages_June13.csv", sep = ",", header = T) %>%
  select(Patient_ID, AOV_REPLACEMENT)

avr_age$AOV_REPLACEMENT[avr_age$AOV_REPLACEMENT >=1000] <- 0

avr_age$decade <- ceiling(avr_age$AOV_REPLACEMENT/10)*10 #25 will become 30, 35 will be 40, etc.

#merge avr with chd categories, filter out just the INFERRED_BAV group, summarize number of inferred bav by decade of procedure (30-100), sum up in cumulative distribution fashion. #Join cumulative summary column with empiric fpr table.

avr_chd <- left_join(select(chd, Patient_ID, MetaCategory), avr_age, by = "Patient_ID") %>%
  filter(MetaCategory == "INFERRED_BAV")

avr_summary_by_decade <- summarize(group_by(avr_chd, decade), N = n())

empiric_fpr$`Inferred AoV Cases` <- c(29,63,138,408,581,583,583,583)

empiric_fpr <- empiric_fpr %>%
  mutate(`Expected False Positives` = round(`Inferred AoV Cases`*FPR,0),
         FP_prop = round(`Expected False Positives`/`Inferred AoV Cases`*100, 0),
         FP_prop_transformed_axis = FP_prop*6)


##Rearrange data
library(tidyr)
tidy_fpr <- gather(empiric_fpr, "Key", "Number of Cases", `Expected False Positives`, `Inferred AoV Cases`) %>%
  arrange(desc(Key)) %>%
  mutate(Key = as.factor(Key)) %>%
  mutate(FP_prop = ifelse(Key == "Expected False Positives", as.numeric(FP_prop), 0),
         FP_prop_transformed_axis = FP_prop*6)


bav_plot <- ggplot(data=tidy_fpr,aes(x=Age, y=`Number of Cases`)) +
  geom_bar(aes(fill=Key, alpha = Key), stat="identity",position ="identity") +
  scale_color_manual(values=c("#c71e1d","black")) +
  scale_fill_manual(values=c("#c71e1d","black")) +
  scale_alpha_manual(values=c(0.8, 0.8)) +
  ggtitle("Expected Proportion of False Positive AoV cases by Age of AoV Replacement") +
  scale_x_continuous("Age of AoV Replacement used as Inclusion Criterion") +
  scale_y_continuous("Number of Cases",sec.axis = sec_axis(~./6, name = "Percent of Cases (%)")) +
  geom_point(data = empiric_fpr, aes(x = Age, y = FP_prop_transformed_axis)) +
  geom_smooth(data = empiric_fpr, aes(x = Age, y = FP_prop_transformed_axis), se = FALSE) +
  geom_text(aes(label=ifelse(FP_prop>3,as.character(FP_prop),''), vjust = 2))

```


```{r detection_bias_sensitivity}
df <- read.csv("detection_bias_sensitivity_Apr23.csv", sep = ",", header = T) %>% select(-c(X, Urine_creatinine, Age_At_Recruitment_0_0, Sex_0_0))

df[df == 2000] <- NA
df <- mutate(df, Any_cancer_0 = as.character(Any_cancer_0))
df$Any_cancer[df$Any_cancer_0 == "" | df$Any_cancer_0 == "missing"] <- NA
df <- mutate(df, Any_cancer_0 = as.factor(Any_cancer_0))

detection <- df %>%
  mutate(Any_cancer = Any_cancer_0) %>%
  mutate(INSITU_BENIGNsurv = as.numeric(ifelse(INSITU_BENIGN <1000, INSITU_BENIGN, 0)),
         SKINsurv = as.numeric(ifelse(SKIN < 1000, SKIN, 0)),
         MI_NO_INTsurv = as.numeric(ifelse(MI_NO_INTERVENTION < 1000, MI_NO_INTERVENTION, 0))) %>%
  mutate(INSITU_BENIGNbin = (ifelse(INSITU_BENIGNsurv == 0, 0, 1)),
         SKINbin = (ifelse(SKINsurv == 0, 0, 1)),
         MI_NO_INTbin = (ifelse(MI_NO_INTsurv == 0, 0, 1))) %>%
  select(Patient_ID, Any_cancer, INSITU_BENIGNsurv, SKINsurv, MI_NO_INTsurv, INSITU_BENIGNbin, SKINbin, MI_NO_INTbin) 

detection_cox <- left_join(select(coxdata, Patient_ID, CHD, CHDsubtype, Age_baseline, Sex, Caucasian, Townsend, Smoking, Alcohol, Weight, BMI, Has_FHx_CVD, BP_systolic_AVG, BP_diastolic_AVG, hypertension_meds, DIABETESprev, HLDprev, Low_activity, Age_at_death, Year_Of_Birth), detection, by = "Patient_ID")

detection_cox <- detection_cox %>%
  mutate(INSITU_BENIGNtime = as.numeric(ifelse(INSITU_BENIGNsurv == 0 & !is.na(Age_at_death), Age_at_death, INSITU_BENIGNsurv)),
         SKINtime = as.numeric(ifelse(SKINsurv == 0 & !is.na(Age_at_death), Age_at_death, SKINsurv)),
         MI_NO_INTtime = as.numeric(ifelse(MI_NO_INTsurv == 0 & !is.na(Age_at_death), Age_at_death, MI_NO_INTsurv))) %>%
  mutate(INSITU_BENIGNtime = as.numeric(ifelse(INSITU_BENIGNsurv == 0 & is.na(Age_at_death), 2016-Year_Of_Birth, INSITU_BENIGNsurv)),
         SKINtime = as.numeric(ifelse(SKINsurv == 0 & is.na(Age_at_death), 2016-Year_Of_Birth, SKINsurv)),
         MI_NO_INTtime = as.numeric(ifelse(MI_NO_INTsurv == 0 & is.na(Age_at_death), 2016-Year_Of_Birth, MI_NO_INTsurv)))


####Logistic regression - detection of any cancer in CHD versus controls by self-report at time of enrollment in UKB

any_cancer_dx_self_reported <- glm(formula = Any_cancer ~ CHD, data = detection_cox, family = "binomial")

#### Cox regression
### MI without any intervention

detection.mi.short <- detection_cox %>%
  mutate(MI_NO_INTtime = MI_NO_INTtime - (Age_baseline-10)) %>%
  filter(MI_NO_INTtime >=0) 

mi <- coxph(Surv(MI_NO_INTtime, MI_NO_INTbin)~CHDsubtype, data = detection.mi.short)

#Simple adjusted
mi.simple <- coxph(Surv(MI_NO_INTtime, MI_NO_INTbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian, data = detection.mi.short)

#Multivariate adjusted
mi.mv <- coxph(Surv(MI_NO_INTtime, MI_NO_INTbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking + Alcohol + Low_activity + Has_FHx_CVD + BMI + BP_systolic_AVG + BP_diastolic_AVG + hypertension_meds + HLDprev + DIABETESprev, data = detection.mi.short)




### In-situ or benign cancerous lesions

detection.insitu.short <- detection_cox %>%
  mutate(INSITU_BENIGNtime = INSITU_BENIGNtime - (Age_baseline-10)) %>%
  filter(INSITU_BENIGNtime >=0) 

insitu <- coxph(Surv(INSITU_BENIGNtime, INSITU_BENIGNbin)~CHDsubtype, data = detection.insitu.short)

#Simple adjusted
insitu.simple <- coxph(Surv(INSITU_BENIGNtime, INSITU_BENIGNbin)~CHDsubtype + Age_baseline + Sex + Townsend + Caucasian + Smoking, data = detection.insitu.short)

```

